---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            auth_basic            "Admin Area";
            auth_basic_user_file  "/etc/nginx/secret/htpasswd";
          }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-sf
        image: nginx:1.21.1-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: "/etc/nginx"
          readOnly: true
        - name: nginx-secret
          mountPath: "/etc/nginx/secret"

      volumes:
        - name: config
          configMap:
            name: nginx-config
            items:
            - key: nginx.conf
              path: nginx.conf
        - name: nginx-secret
          secret:
            secretName: authbasic
            items:
            - key: htpasswd
              path: htpasswd
---
apiVersion: v1
kind: Secret
metadata:
  name: authbasic
data:
  htpasswd: dXNlcjE6JGFwcjEkYzBXakkwNlAkNkFHWDBsZ1A2WUJpbjZXNGxUNFhGMQo=
type: Opaque
---
kind: Service
apiVersion: v1
metadata:
  name: sf-webserver
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
